version: '3.8'

services:
  amazonlite-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: amazonlite-backend
    image: ${REGISTRY:-amazonlite}/backend:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080" # Gateway
      - "8761:8761" # Registry
      - "8081:8081" # Product
      - "8082:8082" # Auth
      - "8083:8083" # Order
      - "8084:8084" # Notification
      - "8085:8085" # Inventory
      - "8086:8086" # Cart
    env_file:
      - ./services/.env
    environment:
      # Use localhost because all services are in the same container now
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://localhost:8761/eureka/"
      EUREKA_INSTANCE_HOSTNAME: "localhost"
      EUREKA_CLIENT_ENABLED: "true"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      DB_URL: "jdbc:postgresql://postgres:5432/amazonlite"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "amazonlite"
      DB_USERNAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
    depends_on:
      - postgres
      - redis
    networks:
      - amazonlite-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - amazonlite-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: amazonlite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - amazonlite-network

  ecommerce-frontend:
    build:
      context: ../ecommerce-frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    networks:
      - amazonlite-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - amazonlite-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./infrastructure/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - amazonlite-network

networks:
  amazonlite-network:
    driver: bridge
