version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - amazonlite-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - amazonlite-network

  product-service:
    build:
      context: ../../services/product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    env_file:
      - ../../services/.env
    environment:
      SPRING_APPLICATION_NAME: product-service
      EUREKA_CLIENT_ENABLED: "false"
    networks:
      - amazonlite-network

  gateway-service:
    build:
      context: ../../services/gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    env_file:
      - ../../services/.env
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      EUREKA_CLIENT_ENABLED: "false"
    depends_on:
      - product-service
    networks:
      - amazonlite-network

  order-service:
    build:
      context: ../../services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    env_file:
      - ../../services/.env
    environment:
      SPRING_APPLICATION_NAME: order-service
      EUREKA_CLIENT_ENABLED: "false"
    networks:
      - amazonlite-network

  notification-service:
    build:
      context: ../../services/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8084:8084"
    env_file:
      - ../../services/.env
    environment:
      SPRING_APPLICATION_NAME: notification-service
      EUREKA_CLIENT_ENABLED: "false"
    networks:
      - amazonlite-network

networks:
  amazonlite-network:
    driver: bridge
